version: "3.8"

services:
  casino-app:
    image: casino-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/casino
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Asdqweres123321
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    depends_on:
      - db
    networks:
      - casino-network

  db:
    image: postgres:15
    container_name: casino-db
    environment:
      POSTGRES_DB: casino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asdqweres123321
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - casino-network

networks:
  casino-network:
    driver: bridge

volumes:
  postgres-data: